import { autoGenerateDrawShiftsSchema } from "@/features/draws/schemas/draws.schema";
import { assertDrawMutationOrigin, drawRouteErrorResponse, drawRouteResponse, getDrawRouteAccessToken, unauthorizedDrawRouteResponse } from "@/features/draws/server/draw-route";
import { drawsApi } from "@/features/draws/server/draws-api";

export async function POST(request: Request) {
  try {
    assertDrawMutationOrigin(request);
    const accessToken = await getDrawRouteAccessToken();
    if (!accessToken) return unauthorizedDrawRouteResponse();
    const input = autoGenerateDrawShiftsSchema.parse(await request.json().catch(() => ({})));
    return drawRouteResponse(await drawsApi.autoGenerateShifts(input, accessToken), 201);
  } catch (error) {
    return drawRouteErrorResponse(error);
  }
}
