"use client";

import { Ban, Eye, ShieldOff, Trash2 } from "lucide-react";
import { DataPagination } from "@/components/ui/data-pagination";
import { useBlockedNumbers } from "../hooks/use-number-control";
import { useNumberControlStore } from "../store/number-control.store";
import type { BlockedNumbersQuery } from "../types/number-control.types";
import { formatControlDate, formatControlDateTime } from "../utils/number-control-formatters";
import { NumberControlBadge } from "./number-control-badge";

export function BlockedNumbersList({ query, basePath, params, canDelete }: { query: BlockedNumbersQuery; basePath: string; params: Record<string, string | number | undefined | null>; canDelete: boolean }) {
  const result = useBlockedNumbers(query);
  const details = useNumberControlStore((state) => state.openBlockDetails);
  const requestDelete = useNumberControlStore((state) => state.requestDeleteBlock);
  const blocks = result.data?.blockedNumbers ?? [];
  const pagination = result.data?.pagination ?? { page: query.page ?? 1, limit: query.limit ?? 10, count: 0, total: 0, totalPages: 0, hasNextPage: false, hasPreviousPage: false };
  if (result.isLoading) return <div className="h-96 animate-pulse rounded-2xl bg-muted" />;
  if (result.error) return <div role="alert" className="rounded-2xl border border-danger/25 bg-danger/10 p-5 text-sm text-danger">{result.error.message}</div>;
  if (!blocks.length) return <div className="rounded-2xl border border-dashed border-border bg-card p-12 text-center"><ShieldOff className="mx-auto h-7 w-7 text-muted-foreground" /><h3 className="mt-4 text-sm font-medium text-foreground">No hay números bloqueados</h3><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">La operación está despejada para los filtros seleccionados.</p></div>;
  return <div className={result.isFetching ? "opacity-65 transition-opacity" : "transition-opacity"}>
    <div className="hidden overflow-x-auto rounded-2xl border border-border bg-card md:block"><table className="w-full min-w-[920px] text-sm"><thead className="border-b border-border bg-muted/60 text-xs text-muted-foreground"><tr><th className="px-5 py-3.5 text-left font-medium">Número</th><th className="px-5 py-3.5 text-left font-medium">Alcance</th><th className="px-5 py-3.5 text-left font-medium">Aplicación</th><th className="px-5 py-3.5 text-left font-medium">Motivo</th><th className="px-5 py-3.5 text-left font-medium">Responsable</th><th className="px-5 py-3.5 text-left font-medium">Registrado</th><th className="px-5 py-3.5 text-right font-medium">Acciones</th></tr></thead><tbody>{blocks.map((block) => <tr key={block.id} className="border-b border-border last:border-0 hover:bg-accent/60"><td className="px-5 py-4"><span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-rose-500 font-mono font-semibold text-white shadow-sm">{block.number}</span></td><td className="px-5 py-4"><NumberControlBadge tone={block.scope === "DATE" ? "warning" : "danger"}>{block.scope === "DATE" ? "Día completo" : "Turno"}</NumberControlBadge></td><td className="px-5 py-4 text-foreground">{block.date ? formatControlDate(block.date) : block.shift ? `${block.shift.configuration.code} · ${formatControlDate(block.shift.date)}` : "—"}</td><td className="max-w-[220px] truncate px-5 py-4 text-muted-foreground">{block.reason ?? "Sin motivo"}</td><td className="px-5 py-4 text-foreground">{block.createdBy?.name ?? block.createdBy?.username ?? "Sistema"}</td><td className="px-5 py-4 text-xs text-muted-foreground">{formatControlDateTime(block.createdAt)}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><button type="button" onClick={() => details(block.id)} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-border px-3 text-xs text-muted-foreground transition hover:bg-accent hover:text-foreground"><Eye className="h-3.5 w-3.5" />Ver</button>{canDelete ? <button type="button" onClick={() => requestDelete(block.id)} className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-rose-500/25 text-rose-700 transition hover:bg-rose-500/10 dark:text-rose-300" aria-label={`Liberar número ${block.number}`}><Trash2 className="h-3.5 w-3.5" /></button> : null}</div></td></tr>)}</tbody></table></div>
    <div className="space-y-3 md:hidden">{blocks.map((block) => <article key={block.id} className="rounded-2xl border border-border bg-card p-4"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-rose-500 font-mono font-semibold text-white">{block.number}</span><div><p className="font-medium text-foreground">{block.date ? formatControlDate(block.date) : block.shift?.configuration.code ?? "Turno"}</p><p className="mt-1 text-xs text-muted-foreground">{block.createdBy?.name ?? block.createdBy?.username ?? "Sistema"}</p></div></div><NumberControlBadge tone="danger">{block.scope === "DATE" ? "Día" : "Turno"}</NumberControlBadge></div><p className="mt-4 line-clamp-2 text-xs leading-5 text-muted-foreground">{block.reason || "Sin motivo registrado."}</p><div className="mt-4 flex gap-2 border-t border-border pt-3"><button type="button" onClick={() => details(block.id)} className="flex h-9 flex-1 items-center justify-center gap-2 rounded-lg border border-border text-xs text-foreground"><Eye className="h-3.5 w-3.5" />Detalles</button>{canDelete ? <button type="button" onClick={() => requestDelete(block.id)} className="flex h-9 flex-1 items-center justify-center gap-2 rounded-lg border border-rose-500/25 text-xs text-rose-700 dark:text-rose-300"><Ban className="h-3.5 w-3.5" />Liberar</button> : null}</div></article>)}</div>
    <DataPagination pagination={pagination} basePath={basePath} params={params} itemLabel="bloqueos" />
  </div>;
}
