"use client";

import { CalendarClock, Gauge, Pencil, TimerOff } from "lucide-react";
import { DataPagination } from "@/components/ui/data-pagination";
import { useNumberLimits } from "../hooks/use-number-control";
import { useNumberControlStore } from "../store/number-control.store";
import type { NumberLimitsQuery } from "../types/number-control.types";
import { formatControlDate, formatLimitMiles, isNumberLimitActive } from "../utils/number-control-formatters";
import { NumberControlBadge } from "./number-control-badge";

export function NumberLimitsList({ query, basePath, params, canUpdate }: { query: NumberLimitsQuery; basePath: string; params: Record<string, string | number | undefined | null>; canUpdate: boolean }) {
  const result = useNumberLimits(query);
  const edit = useNumberControlStore((state) => state.openEditLimit);
  const expire = useNumberControlStore((state) => state.requestExpireLimit);
  const limits = result.data?.limits ?? [];
  const pagination = result.data?.pagination ?? { page: query.page ?? 1, limit: query.limit ?? 10, count: 0, total: 0, totalPages: 0, hasNextPage: false, hasPreviousPage: false };

  if (result.isLoading) return <div className="h-96 animate-pulse rounded-2xl bg-muted" />;
  if (result.error) return <div role="alert" className="rounded-2xl border border-danger/25 bg-danger/10 p-5 text-sm text-danger">{result.error.message}</div>;
  if (!limits.length) return <div className="rounded-2xl border border-dashed border-border bg-card p-12 text-center"><Gauge className="mx-auto h-7 w-7 text-muted-foreground" /><h3 className="mt-4 text-sm font-medium text-foreground">No hay límites para estos filtros</h3><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">Ajusta la búsqueda o crea una regla para controlar la exposición de venta.</p></div>;

  return <div className={result.isFetching ? "opacity-65 transition-opacity" : "transition-opacity"}>
    <div className="hidden overflow-x-auto rounded-2xl border border-border bg-card md:block"><table className="w-full min-w-[980px] text-sm"><thead className="border-b border-border bg-muted/60 text-xs text-muted-foreground"><tr><th className="px-5 py-3.5 text-left font-medium">Número</th><th className="px-5 py-3.5 text-left font-medium">Tope</th><th className="px-5 py-3.5 text-left font-medium">Vendedor</th><th className="px-5 py-3.5 text-left font-medium">Sorteo</th><th className="px-5 py-3.5 text-left font-medium">Vigencia</th><th className="px-5 py-3.5 text-left font-medium">Estado</th><th className="px-5 py-3.5 text-right font-medium">Acciones</th></tr></thead><tbody>{limits.map((limit) => {
      const active = isNumberLimitActive(limit.validFrom, limit.validUntil);
      return <tr key={limit.id} className="border-b border-border last:border-0 hover:bg-accent/60"><td className="px-5 py-4"><span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-primary font-mono font-semibold text-primary-foreground shadow-sm">{limit.number}</span></td><td className="px-5 py-4"><p className="font-mono font-semibold tabular-nums text-foreground">{formatLimitMiles(limit.limitMiles)}</p><p className="mt-0.5 text-[11px] text-muted-foreground">miles</p></td><td className="px-5 py-4 text-foreground">{limit.seller?.name ?? "Todos"}</td><td className="px-5 py-4 text-foreground">{limit.drawConfiguration?.code ?? "Todos"}</td><td className="px-5 py-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><CalendarClock className="h-3.5 w-3.5" />{formatControlDate(limit.validFrom)} – {limit.validUntil ? formatControlDate(limit.validUntil) : "Sin cierre"}</span></td><td className="px-5 py-4"><NumberControlBadge tone={active ? "success" : "neutral"}>{active ? "Vigente" : "Fuera de vigencia"}</NumberControlBadge></td><td className="px-5 py-4"><div className="flex justify-end gap-1">{canUpdate ? <><button type="button" onClick={() => edit(limit.id)} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-border px-3 text-xs text-muted-foreground transition hover:bg-accent hover:text-foreground"><Pencil className="h-3.5 w-3.5" />Editar</button>{active ? <button type="button" onClick={() => expire(limit.id)} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-amber-500/25 px-3 text-xs text-amber-700 transition hover:bg-amber-500/10 dark:text-amber-300"><TimerOff className="h-3.5 w-3.5" />Finalizar</button> : null}</> : <span className="text-xs text-muted-foreground">Solo lectura</span>}</div></td></tr>;
    })}</tbody></table></div>
    <div className="space-y-3 md:hidden">{limits.map((limit) => { const active = isNumberLimitActive(limit.validFrom, limit.validUntil); return <article key={limit.id} className="rounded-2xl border border-border bg-card p-4"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary font-mono font-semibold text-primary-foreground">{limit.number}</span><div><p className="font-mono font-semibold text-foreground">{formatLimitMiles(limit.limitMiles)} miles</p><p className="mt-1 text-xs text-muted-foreground">{limit.seller?.name ?? "Global"} · {limit.drawConfiguration?.code ?? "Todos los sorteos"}</p></div></div><NumberControlBadge tone={active ? "success" : "neutral"}>{active ? "Vigente" : "Finalizado"}</NumberControlBadge></div><p className="mt-4 text-xs text-muted-foreground">{formatControlDate(limit.validFrom)} – {limit.validUntil ? formatControlDate(limit.validUntil) : "Sin cierre"}</p>{canUpdate ? <div className="mt-4 flex gap-2 border-t border-border pt-3"><button type="button" onClick={() => edit(limit.id)} className="flex h-9 flex-1 items-center justify-center gap-2 rounded-lg border border-border text-xs text-foreground"><Pencil className="h-3.5 w-3.5" />Editar</button>{active ? <button type="button" onClick={() => expire(limit.id)} className="flex h-9 flex-1 items-center justify-center gap-2 rounded-lg border border-amber-500/25 text-xs text-amber-700 dark:text-amber-300"><TimerOff className="h-3.5 w-3.5" />Finalizar</button> : null}</div> : null}</article>; })}</div>
    <DataPagination pagination={pagination} basePath={basePath} params={params} itemLabel="límites" />
  </div>;
}
