export const routes = {
  home: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  passwordReset: "/restablecer-contrasena",
  sellerActivation: "/activar-vendedor",

  dashboard: "/dashboard",
  sales: "/ventas",
  salesMatrix: "/matriz-ventas",
  draws: "/sorteos",
  shifts: "/turnos",
  numberControl: "/control-numerico",
  blockedNumbers: "/numeros-bloqueados",
  numberLimits: "/limites",
  results: "/resultados",
  prizePayments: "/premios",
  cashCuts: "/cortes",
  reports: "/reportes",
  sellers: "/vendedores",
  users: "/usuarios",
  parameters: "/parametros",
  roles: "/roles",
  audit: "/auditoria",
  settings: "/ajustes",
  subscription: "/suscripcion",
  platform: "/plataforma",
} as const;
