"use client";

import { Ban, Eye, ReceiptText } from "lucide-react";
import { DataPagination } from "@/components/ui/data-pagination";
import { useSales } from "../hooks/use-sales";
import { useSalesWorkspaceStore } from "../store/sales-workspace.store";
import type { SalesQuery } from "../types/sales.types";
import { formatMiles, formatSaleDateTime } from "../utils/sales-formatters";
import { SaleStatusBadge } from "./sale-status-badge";

export function SalesList({ query, basePath, params, canUpdate }: { query: SalesQuery; basePath: string; params: Record<string, string | number | undefined | null>; canUpdate: boolean }) {
  const result = useSales(query);
  const openDetails = useSalesWorkspaceStore((state) => state.openSaleDetails);
  const requestVoid = useSalesWorkspaceStore((state) => state.requestVoid);
  const sales = result.data?.sales ?? [];
  const pagination = result.data?.pagination ?? { page: query.page ?? 1, limit: query.limit ?? 10, count: 0, total: 0, totalPages: 0, hasNextPage: false, hasPreviousPage: false };
  if (result.isLoading) return <div className="h-96 animate-pulse rounded-2xl bg-muted" />;
  if (result.error) return <div role="alert" className="rounded-2xl border border-danger/25 bg-danger/10 p-5 text-sm text-danger">{result.error.message}</div>;
  if (!sales.length) return <div className="rounded-2xl border border-dashed border-border bg-card p-12 text-center"><ReceiptText className="mx-auto h-7 w-7 text-muted-foreground" /><h3 className="mt-4 text-sm font-medium text-foreground">No hay ventas para estos filtros</h3><p className="mt-2 text-sm text-muted-foreground">Ajusta la búsqueda o registra el primer ticket.</p></div>;
  return <div className={result.isFetching ? "opacity-65 transition-opacity" : "transition-opacity"}><div className="hidden overflow-x-auto rounded-2xl border border-border bg-card md:block"><table className="w-full min-w-[980px] text-sm"><thead className="border-b border-border bg-muted/60 text-xs text-muted-foreground"><tr><th className="px-5 py-3.5 text-left font-medium">Ticket</th><th className="px-5 py-3.5 text-left font-medium">Vendedor</th><th className="px-5 py-3.5 text-left font-medium">Sorteo</th><th className="px-5 py-3.5 text-left font-medium">Jugadas</th><th className="px-5 py-3.5 text-left font-medium">Total</th><th className="px-5 py-3.5 text-left font-medium">Registrada</th><th className="px-5 py-3.5 text-left font-medium">Estado</th><th className="px-5 py-3.5 text-right font-medium">Acciones</th></tr></thead><tbody>{sales.map((sale) => <tr key={sale.id} className="border-b border-border last:border-0 hover:bg-accent/60"><td className="px-5 py-4 font-mono text-xs text-foreground">#{sale.id.slice(0, 8).toUpperCase()}</td><td className="px-5 py-4 text-foreground">{sale.seller.name}</td><td className="px-5 py-4 text-foreground">{sale.shift?.configuration.code ?? "—"}</td><td className="px-5 py-4"><div className="flex max-w-[190px] flex-wrap gap-1">{sale.details.slice(0, 5).map((detail) => <span key={detail.id} className="rounded-md border border-border bg-muted px-1.5 py-0.5 font-mono text-[10px] text-foreground">{detail.number}</span>)}{sale.details.length > 5 ? <span className="text-[10px] text-muted-foreground">+{sale.details.length - 5}</span> : null}</div></td><td className="px-5 py-4 font-mono font-semibold text-foreground">{formatMiles(sale.totalMiles)} mil</td><td className="px-5 py-4 text-xs text-muted-foreground">{formatSaleDateTime(sale.createdAt)}</td><td className="px-5 py-4"><SaleStatusBadge status={sale.status} /></td><td className="px-5 py-4"><div className="flex justify-end gap-1"><button type="button" onClick={() => openDetails(sale.id)} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-border px-3 text-xs text-muted-foreground transition hover:bg-accent hover:text-foreground"><Eye className="h-3.5 w-3.5" />Ver</button>{canUpdate && sale.status === "ACTIVA" && sale.shift?.status === "ABIERTO" ? <button type="button" onClick={() => requestVoid(sale.id)} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-rose-500/25 px-3 text-xs text-rose-700 transition hover:bg-rose-500/10 dark:text-rose-300"><Ban className="h-3.5 w-3.5" />Anular</button> : null}</div></td></tr>)}</tbody></table></div>
    <div className="space-y-3 md:hidden">{sales.map((sale) => <article key={sale.id} className="rounded-2xl border border-border bg-card p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs font-medium text-foreground">#{sale.id.slice(0, 8).toUpperCase()}</p><p className="mt-1 text-xs text-muted-foreground">{sale.seller.name} · {sale.shift?.configuration.code ?? "Sin turno"}</p></div><SaleStatusBadge status={sale.status} /></div><div className="mt-4 flex items-end justify-between"><div><p className="text-xs text-muted-foreground">{sale.details.length} jugadas</p><p className="mt-1 font-mono text-lg font-semibold text-foreground">{formatMiles(sale.totalMiles)} mil</p></div><p className="text-xs text-muted-foreground">{formatSaleDateTime(sale.createdAt)}</p></div><div className="mt-4 flex gap-2 border-t border-border pt-3"><button type="button" onClick={() => openDetails(sale.id)} className="flex h-9 flex-1 items-center justify-center gap-2 rounded-lg border border-border text-xs text-foreground"><Eye className="h-3.5 w-3.5" />Detalles</button>{canUpdate && sale.status === "ACTIVA" && sale.shift?.status === "ABIERTO" ? <button type="button" onClick={() => requestVoid(sale.id)} className="flex h-9 flex-1 items-center justify-center gap-2 rounded-lg border border-rose-500/25 text-xs text-rose-700 dark:text-rose-300"><Ban className="h-3.5 w-3.5" />Anular</button> : null}</div></article>)}</div><DataPagination pagination={pagination} basePath={basePath} params={params} itemLabel="ventas" /></div>;
}
