import { CalendarClock, CircleUserRound, Hash, Ticket } from "lucide-react";
import type { Sale } from "../types/sales.types";
import { formatMiles, formatSaleDate, formatSaleDateTime } from "../utils/sales-formatters";
import { SaleStatusBadge } from "./sale-status-badge";
import { SalePrintButton } from "./sale-print-button";

export function SaleDetailContent({ sale }: { sale: Sale }) {
  return <div className="space-y-5"><section className="rounded-2xl border border-border bg-muted/30 p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Ticket</p><p className="mt-2 font-mono text-lg font-semibold text-foreground">#{sale.id.slice(0, 12).toUpperCase()}</p></div><SaleStatusBadge status={sale.status} /></div><p className="mt-4 font-mono text-3xl font-semibold text-foreground">{formatMiles(sale.totalMiles)} <span className="text-sm font-normal text-muted-foreground">miles</span></p><SalePrintButton sale={sale} className="mt-5 w-full gap-2" /></section>
    <dl className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-border p-4"><dt className="flex items-center gap-2 text-xs text-muted-foreground"><CircleUserRound className="h-3.5 w-3.5" />Vendedor</dt><dd className="mt-2 text-sm font-medium text-foreground">{sale.seller.name}</dd></div><div className="rounded-2xl border border-border p-4"><dt className="flex items-center gap-2 text-xs text-muted-foreground"><CalendarClock className="h-3.5 w-3.5" />Registrada</dt><dd className="mt-2 text-sm font-medium text-foreground">{formatSaleDateTime(sale.createdAt)}</dd></div><div className="rounded-2xl border border-border p-4 sm:col-span-2"><dt className="flex items-center gap-2 text-xs text-muted-foreground"><Ticket className="h-3.5 w-3.5" />Turno</dt><dd className="mt-2 text-sm font-medium text-foreground">{sale.shift ? `${sale.shift.configuration.code} · ${formatSaleDate(sale.shift.date)} · ${sale.shift.configuration.time.slice(0, 5)}` : "Sin turno asociado"}</dd></div></dl>
    <section><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 text-sm font-semibold text-foreground"><Hash className="h-4 w-4" />Jugadas</h3><span className="text-xs text-muted-foreground">{sale.details.length} números</span></div><div className="mt-3 space-y-2">{sale.details.map((detail) => <div key={detail.id} className="flex items-center justify-between rounded-xl border border-border bg-background p-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary font-mono font-semibold text-primary-foreground">{detail.number}</span><span className="font-mono text-sm font-semibold text-foreground">{formatMiles(detail.prizeMiles)} mil</span></div>)}</div></section>
    {sale.status === "ANULADA" ? <section className="rounded-2xl border border-rose-500/25 bg-rose-500/8 p-4"><p className="text-xs font-medium uppercase tracking-[0.14em] text-rose-700 dark:text-rose-300">Anulación</p><p className="mt-2 text-sm text-foreground">{sale.voidReason || "Sin motivo registrado."}</p>{sale.voidedAt ? <p className="mt-2 text-xs text-muted-foreground">{formatSaleDateTime(sale.voidedAt)}</p> : null}</section> : null}
  </div>;
}
